### PR TITLE
Solved "NoSuchMethodError", arising from WorldEdit

### PR DESCRIPTION
**Pull request by akaregi**
I've fixed an error discussing on issue #2 . This PR solves `NoSuchMethodError` arising from WorldEdit, due to changing its implementation for Vector3.

And I tested this in my local server. It seems work very well. 

Below is a list for changing point by this PR:
* Version. `1.2.0` => `1.3.0`
* Name. `Expansion-WorldGuard` => `WorldGuard-Expansion`
* The code.

Regards,
akaregi

### CODE REVIEW

**Comment by akaregi** [comment]
If you want to test this, you can download this PR's build at my forked repository!
https://github.com/akaregi/WorldGuard-Expansion/releases/tag/pre-2

**Comment by OverCrave** [comment]
I tried this on my main server and can confirm that it works great!

**Comment by darbyjack** [comment]
Thanks. Will add it in shortly!

**Comment by extendedclip** [comment]
Ty @akaregi. One concern is this does make the expansion compatible with newer versions of WG / WE but does this new method break backwards compatibility? If so I think we should use some abstraction and version checking to provide compatibility with older and current world guard versions. What you think?

**Comment by darbyjack** [comment]
There's a repo we can use called a World guard wrapper if we need to.

**Comment by akaregi** [comment]
@extendedclip 
Propably no. It seems that WorldEdit only leaves new `Vector3` function and doesn't support backwards compatibility. Also, WorldGuard depend on new things of WE. It means we have to use the wrapper or something to support former function.

But I have no idea how to do this, so now I won't support backwards compatibilty(i.e. WE with old "Vector" function). Sorry.

**Pull request merged**
